In [1]:
# 1. 1D Array Slicing
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# 1. Elements from index 2 to 6 (6 excluded)
print(arr[2:6])

# 2. Every second element
print(arr[::2])

# 3. Reverse the array
print(arr[::-1])

# 4. Last 4 elements
print(arr[-4:])

# 5. Index 1 to 7 with step 2
print(arr[1:8:2])

[30 40 50 60]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]
[60 70 80 90]
[20 40 60 80]


In [2]:
# 2. 2D Array Slicing
import numpy as np

arr_2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

# 1. Second row
print(arr_2d[1])

# 2. Third column
print(arr_2d[:, 2])

# 3. Every alternate column
print(arr_2d[:, ::2])

# 4. Bottom-right 2×2 sub-array
print(arr_2d[-2:, -2:])

[ 6  7  8  9 10]
[ 3  8 13 18]
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]]
[[14 15]
 [19 20]]


In [3]:
# 3. 3D Array Slicing
import numpy as np

arr_3d = np.arange(1, 25).reshape(2, 3, 4)

# 1. Second row from every 2D slice
print(arr_3d[:, 1, :])

# 2. Last column from every 2D slice
print(arr_3d[:, :, -1])

# 3. Top-left (2,2,2) sub-array
print(arr_3d[:, :2, :2])

# 4. Corners of first and last rows
print(arr_3d[:, [0, -1], :][:, :, [0, -1]])

[[ 5  6  7  8]
 [17 18 19 20]]
[[ 4  8 12]
 [16 20 24]]
[[[ 1  2]
  [ 5  6]]

 [[13 14]
  [17 18]]]
[[[ 1  4]
  [ 9 12]]

 [[13 16]
  [21 24]]]
