In [1]:
#Q1. 1D NumPy Array
import numpy as np
arr = np.arange(10, 51, 5)
print("Array:", arr)
print("3rd element:", arr[2])
print("Last element:", arr[-1])

Array: [10 15 20 25 30 35 40 45 50]
3rd element: 20
Last element: 50


In [2]:
#Q2. 2D NumPy Array
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print("Element:", arr[1][2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element: 7


In [3]:
#Q3. 3D NumPy Array
import numpy as np
arr = np.arange(1, 25).reshape(2, 3, 4)
print(arr)
print("Element:", arr[0][1][2])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Element: 7


In [4]:
#4(a). Mean, Median, Variance and Standard Deviation
import numpy as np
a = np.array([12,32,56,32,87,65,45,32,12,32])
print("Mean =", np.mean(a))
print("Median =", np.median(a))
print("Variance =", np.var(a))
print("Standard Deviation =", np.std(a))

Mean = 40.5
Median = 32.0
Variance = 493.65
Standard Deviation = 22.21823575354263


In [5]:
#4(b). Mean, Median, Variance and Standard Deviation
import numpy as np
b = np.array([34,56,87,98,12,43,21,45,67,87,22,43])
print("Mean =", np.mean(b))
print("Median =", np.median(b))
print("Variance =", np.var(b))
print("Standard Deviation =", np.std(b))

Mean = 51.25
Median = 44.0
Variance = 733.0208333333334
Standard Deviation = 27.074357486990035
